/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class Choice extends javax.swing.JFrame {

    /**
     * Creates new form Choice
     */
    public Choice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultButton = new javax.swing.JLabel();
        LabButton = new javax.swing.JLabel();
        Choice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HEALTHCARE APPOINTMENT");
        setMaximumSize(new java.awt.Dimension(550, 290));
        setMinimumSize(new java.awt.Dimension(550, 290));
        setPreferredSize(new java.awt.Dimension(550, 290));
        setResizable(false);
        getContentPane().setLayout(null);

        ConsultButton.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        ConsultButton.setForeground(new java.awt.Color(255, 255, 255));
        ConsultButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConsultButton.setText("CONSULTATION");
        ConsultButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ConsultButton);
        ConsultButton.setBounds(170, 96, 210, 40);

        LabButton.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        LabButton.setForeground(new java.awt.Color(255, 255, 255));
        LabButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabButton.setText("LABORATORY");
        LabButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabButtonMouseClicked(evt);
            }
        });
        getContentPane().add(LabButton);
        LabButton.setBounds(170, 140, 210, 40);

        Choice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Choice.jpg"))); // NOI18N
        Choice.setMaximumSize(new java.awt.Dimension(595, 275));
        Choice.setMinimumSize(new java.awt.Dimension(595, 275));
        Choice.setPreferredSize(new java.awt.Dimension(595, 275));
        getContentPane().add(Choice);
        Choice.setBounds(0, 0, 550, 280);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultButtonMouseClicked
        // TODO add your handling code here:
        ConsultMenu s;
        try {
            s = new ConsultMenu();
            s.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Choice.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);

    }//GEN-LAST:event_ConsultButtonMouseClicked

    private void LabButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabButtonMouseClicked
        // TODO add your handling code here:
        LabMenu s = new LabMenu();
        this.setVisible(false);
        s.setVisible(true);

    }//GEN-LAST:event_LabButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Choice;
    private javax.swing.JLabel ConsultButton;
    private javax.swing.JLabel LabButton;
    // End of variables declaration//GEN-END:variables
}
