/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ArrayList<String> User = new ArrayList();
    String Doctor;
    File Passwords;
    Scanner read;

    public Login() throws FileNotFoundException {
        User.add("issam");
        User.add("dany");
        User.add("shakib");
        User.add("joe");
        User.add("lab1");
        User.add("lab2");
        User.add("lab3");
        User.add("lab4");
        initComponents();
        jtfUsername.setBackground(new java.awt.Color(0, 0, 0, 1));
        jPasswordField.setBackground(new java.awt.Color(0, 0, 0, 1));
        jPasswordField.setEchoChar((char) 0);
        hide.setVisible(false);
        show.setVisible(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        Logbutton = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setMaximumSize(new java.awt.Dimension(550, 290));
        setMinimumSize(new java.awt.Dimension(550, 290));
        setPreferredSize(new java.awt.Dimension(550, 290));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jtfUsername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jtfUsername.setForeground(new java.awt.Color(255, 255, 255));
        jtfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfUsername.setText("USERNAME");
        jtfUsername.setBorder(null);
        jtfUsername.setFocusCycleRoot(true);
        jtfUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfUsernameMousePressed(evt);
            }
        });
        getContentPane().add(jtfUsername);
        jtfUsername.setBounds(170, 102, 210, 30);

        jPasswordField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField.setText("PASSWORD");
        jPasswordField.setBorder(null);
        jPasswordField.setOpaque(false);
        jPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldMousePressed(evt);
            }
        });
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordField);
        jPasswordField.setBounds(170, 142, 210, 40);

        Logbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(Logbutton);
        Logbutton.setBounds(170, 190, 210, 40);

        show.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\show_hide07-frfr512.png")); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        getContentPane().add(show);
        show.setBounds(390, 150, 30, 20);

        hide.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\unnamed.png")); // NOI18N
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        getContentPane().add(hide);
        hide.setBounds(390, 150, 30, 20);

        Login.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\calm-breeze-login-screen.jpg")); // NOI18N
        Login.setText("jLabel4");
        getContentPane().add(Login);
        Login.setBounds(0, 0, 550, 280);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 10, 10, 22);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogbuttonMouseClicked
        // TODO add your handling code here:
        File Pass = new File("Passwords.dat");
        try {
            read = new Scanner(Pass);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        int found = 0;
        String user = jtfUsername.getText();
        String pass = jPasswordField.getText();
        for (int i = 0; i < User.size(); i++) {
            if (user.equals(User.get(i))) {
                found = 1;
                for (int x = 0; x < i; x++) {
                    read.nextLine();
                }
                read.next();
                if (pass.equals(read.next())) {
                    EmployeeMenu s;
                    try {
                        s = new EmployeeMenu(i + 1);
                        this.setVisible(false);
                        s.setVisible(true);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    found = 2;
                    break;
                }
            }
        }
        if (found == 1) {
            JOptionPane.showMessageDialog(null, "You've Entered An Incorrect Password.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (found == 0) {
            JOptionPane.showMessageDialog(null, "You've Entered An Incorrect Username.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LogbuttonMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        // TODO add your handling code here:
        jPasswordField.setEchoChar((char) 0);
        show.setVisible(false);
        hide.setVisible(true);
    }//GEN-LAST:event_showMouseClicked

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        // TODO add your handling code here:
        jPasswordField.setEchoChar('\u25cf');
        hide.setVisible(false);
        show.setVisible(true);
    }//GEN-LAST:event_hideMouseClicked

    private void jPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_SPACE) {
            jPasswordField.setEditable(false);
        } else {
            jPasswordField.setEditable(true);
            show.setVisible(true);
        }


    }//GEN-LAST:event_jPasswordFieldKeyTyped

    private void jtfUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfUsernameMousePressed
        // TODO add your handling code here:
        if (jPasswordField.getText().equals("")) {
            jPasswordField.setEchoChar((char) 0);
            jPasswordField.setText("PASSWORD");
            show.setVisible(false);
            hide.setVisible(false);
        }
        if (jtfUsername.getText().equals("USERNAME")) {
            jtfUsername.setText("");
        }
    }//GEN-LAST:event_jtfUsernameMousePressed

    private void jPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMousePressed
        // TODO add your handling code here:
        if (jtfUsername.getText().equals("")) {
            jtfUsername.setText("USERNAME");
        }
        if (jPasswordField.getText().equals("PASSWORD")) {
            jPasswordField.setText("");
        }
        jPasswordField.setEchoChar('\u25cf');
    }//GEN-LAST:event_jPasswordFieldMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logbutton;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel hide;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtfUsername;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
